### ISSUE TITLE
Landing page design improvements

### ISSUE THREAD

**Issue by KennethWussmann** [extiverse/bazaar#103]
### Steps to reproduce
1. Open the landing page (logged out): https://flagrow.io/

### Actual behaviour
1. In the extensions panel, the menu dots get white on hover - It seems like they disappear, because of the gray background
![](https://i.imgur.com/tVYBI5T.png)
2. The labels of the register/login buttons are not aligned vertical correctly
![](https://i.imgur.com/qRmblGK.png)
3. The responsive navigation has no background color, that's why it does not look that good.
![](https://i.imgur.com/3XHLvv6.png)
4. The hamburger menu of the responsive navigation could have a little more spacing from the right
5. The headings of the responsive view could have a little more spacing from the left of the screen. (Also the extension panels don't have spacing from left and right)
![](https://i.imgur.com/2LO9ISX.png)
6. The fixed navigation of the responsive view is not fixed at the top correctly
![](https://i.imgur.com/dpey48S.png)
7. The pagination left/right buttons at the bottom of the extension panels are not good visible. Maybe use the `chevron-left`/`chevron-right` of Fontawesome. (For sure, with the `«` chars it will always be visible, also for people with accessibility features turned on. But it's not good visible for all others)
![](https://i.imgur.com/cR6UKTU.png)

### Configuration

**Operating system - Desktop:** Windows 10 Pro / Google Chrome 63.0.3239.132
**Operating system - Mobile:** Android 8.1.0 / Google Chrome 64.0.3282.123

**Version of Bazaar:** Issue related to the public landing page
**Version of Flarum:** -
**Other extensions:** -

**Comment by darisi** [comment]
will sort this one 👍

**Comment by luceos** [comment]
Redesign makes this obsolete.
