### ISSUE TITLE
Define supported platforms

### ISSUE THREAD

**Issue by clarkwinkelmann** [extiverse/bazaar#114]
Re-reading through the issues I notice we often have issues with uncommon setups.

With the incoming premium extensions features, we can't afford to have broken setups like that pop up so often. We also need to clear these issues from the tracker instead of keeping them opened forever.

I suggest we define the following:

- Server OS supported
- Webserver supported
- Database supported
- Browsers supported to use the GUI

We don't need to block access to others, but we won't offer support.

In particular I'm thinking of officially dropping support for:

- Windows/IIS. Unless we get a Windows developer onboard we just can't troubleshoot issues with that
- MariaDB. There are so many weird things with Flarum and MariaDB right now
- Mobile browsers, Unless we refactor the UI to be more responsive I don't think it makes sense to troubleshoot mobile issues. Also the premium checkout process is not optimized for mobile at all, and I don't think it would make any particular sense at this time

This would give us something like this:

- Linux
- Apache/Nginx
- MySQL
- Latest Firefox/Chrome

Browser support should probably be the same as whatever we define for flagrow.io dashboard.

What do you think @luceos ?

**Comment by luceos** [comment]
I agree, we need to clearly spec out the requirements.

**Comment by hardware** [comment]
Which versions of PHP are supported ?

**Comment by luceos** [comment]
The same ones Flarum does: php 5.6 (until beta 8), php 7.0 and 7.1. I think we'll hit PHP 7.2 with Flarum beta 8.
