### ISSUE TITLE
Extention... not installing?

### ISSUE THREAD

**Issue by ScribbleNerd** [extiverse/bazaar#134]
### Steps to reproduce
I don't know if this is going to happen elsewhere but heres what I did...
1. I SSHed into my server
2. typed the command `composer require flagrow/bazaar`

### Expected behaviour
Composer installes bazaar

Tell us what should happen
Composer should install bazaar within a couple minutes

### Actual behaviour
Installation seems to hang

Tell us what happens instead
The installation hangs, the output goes as follows:
C:\Users\mypc'susername>ssh username@server'sip
Password: passwordistypedbutnotdisplayed
Last login: Mon Jul  1 02:06:02 2019 from mypc'sip
Last login: Mon Jul  1 02:06:02 2019 from mypc'sip
Computer Name:~ accountname$ cd path/to/forum/root/folder
Minecraft-Server:forum scribbleplex$ composer require flagrow/bazaar
Using version ^0.3.10 for flagrow/bazaar
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 13 installs, 0 updates, 0 removals
  - Installing symfony/process (v3.4.29): Downloading (100%)
  - Installing mtdowling/cron-expression (v1.2.1): Downloading (100%)
  - Installing illuminate/console (v5.5.44): Downloading (100%)
  - Installing flagrow/console (0.4.3): Downloading (100%)
  - Installing seld/phar-utils (1.0.1): Downloading (100%)
  - Installing seld/jsonlint (1.7.1): Downloading (100%)
  - Installing justinrainbow/json-schema (5.2.8): Downloading (100%)
  - Installing composer/xdebug-handler (1.3.3): Downloading (100%)
  - Installing composer/spdx-licenses (1.5.1): Downloading (100%)
  - Installing composer/semver (1.5.0): Downloading (100%)
  - Installing composer/ca-bundle (1.1.4): Downloading (100%)
  - Installing composer/composer (1.8.6): Downloading (100%)
  - Installing flagrow/bazaar (0.3.10): Downloading (100%)
Package s9e/flarum-ext-mediaembed is abandoned, you should avoid using it. Use fof/formatting instead.
Package flagrow/console is abandoned, you should avoid using it. Use fof/console instead.
Writing lock file
Generating autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
and then it does nothing even after having the window open for 30 minutes

### Configuration

**Operating system:** 
macOS 10.13 - High Sierra
**Version of Bazaar:** 
0.3.10
**Version of Flarum:** 
0.1.0-beta.8.2
**Other extensions:** 

Enabled:
AutoImage 1.1.0
AutoVideo 1.1.0
BBCode 0.1.0-beta.8
Byōbu 0.2.2
Email verification switch 0.1.3
Emoji 0.1.0-beta.8
Emoji Picker 0.2.0
English 0.1.0-beta.8
Flagrow Direct Links 0.2.0
Flagrow Sitemap 0.2.0
Flags 0.1.0-beta.8.1
FoF Discord Login 0.1.2
FoF Prevent Necrobumping 0.1.3
FoF User Direcory 0.3.1
Google Login 0.1.0-beta.8.0.3
Imgur Upload 3.3.0
Likes 0.1.0-beta.8.1
Lock 0.1.0-beta.8
Markdown 0.1.0-beta.8
Markdown Tables 1.0.9
MediaEmbed 1.0.0
Mentions 0.1.0-beta.8.1
Pusher 0.1.0-beta.8.1
ReFlar Gamification 3.1.2
Reflar Level Ranks 1.2.1
Reflar Polls 1.3.4
Reflar Reactions 1.0.0-beta.5.2
ReFlar Two Factor 0.1.2
Reflar Webhooks 0.1.7
Statistics 0.1.0-beta.8
Sticky 0.1.0-beta.8
Subscriptions 0.1.0-beta.8
Summaries 0.3.1
Suspend 0.1.0-beta.8
Tags 0.1.0-beta.8.2
Upload 0.7.1
Disabled:
Approval 0.1.0-beta.8
Facebook Login 0.1.0-beta.8
GitHub Login 0.1.0-beta.8
Twitter Login 0.1.0-beta.8
<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by ScribbleNerd** [comment]
eventually did ctrl+c and I guess it installed and just didn't tell me???

**Comment by luceos** [comment]
the last few lines actually state it worked, but that's perhaps advanced composer knowledge:

```
Writing lock file
Generating autoload files
```

Thanks for reporting and glad it installed anyway.
