### ISSUE TITLE
Bazaar Activated but no add-ins listed - Missing Token?

### ISSUE THREAD

**Issue by darossi81** [extiverse/bazaar#140]
### Steps to reproduce

1. Installed Flarum and Bazaar using PocketHold
2. Switched Bazaar on in Extensions
3. No marketplace/extensions listed

### Expected behaviour

I expected to see a list of extensions.

### Actual behaviour

I see no list of extensions and also if I try to connect to flagrow I get a blank page. I've also noticed that there is no API token.

### Configuration

Using shared hosting on Linux.

**Version of Bazaar:**  0.4.1
**Version of Flarum:** 0.1.0-beta.11.1
**Other extensions:** none

<details><summary>**Logs**:</summary>
[2020-01-06 16:32:06] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:32:14] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:32:14] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:32:18] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:32:22] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:32:32] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:32:39] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:32:43] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:32:44] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:32:45] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:32:46] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:32:49] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:34:13] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:34:31] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:34:40] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:35:04] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:36:42] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:38:32] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:38:35] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:38:50] production.ERROR: Exception: Connecting failed in /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flagrow/bazaar/src/Api/Controllers/ConnectController.php:35
Stack trace:
#0 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): Extiverse\Bazaar\Api\Controllers\ConnectController->handle(Object(Zend\Diactoros\ServerRequest))
#1 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(65): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}(Object(Zend\Diactoros\ServerRequest), Array)
#2 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\DispatchRoute->process(Object(Zend\Diactoros\ServerRequest), Object(Closure))
#3 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#4 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\SetLocale->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#5 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(23): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#6 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\CheckCsrfToken->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#7 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#8 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\AuthenticateWithHeader->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#9 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#10 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\AuthenticateWithSession->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#11 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(51): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#12 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\RememberFromCookie->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#13 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#14 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\StartSession->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#15 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#16 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Api\Middleware\FakeHttpMethods->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#17 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#18 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\ParseJsonBody->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#19 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#20 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\HandleErrors->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#21 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(83): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#22 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/middlewares/request-handler/src/RequestHandler.php(84): Zend\Stratigility\MiddlewarePipe->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#23 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\RequestHandler->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#24 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#25 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\BasePathRouter->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#26 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Middleware/OriginalMessages.php(41): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#27 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Zend\Stratigility\Middleware\OriginalMessages->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#28 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/middlewares/base-path/src/BasePath.php(53): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#29 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\BasePath->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#30 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(83): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#31 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(72): Zend\Stratigility\MiddlewarePipe->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\EmptyPipelineHandler))
#32 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-httphandlerrunner/src/RequestHandlerRunner.php(95): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diactoros\ServerRequest))
#33 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Server.php(44): Zend\HttpHandlerRunner\RequestHandlerRunner->run()
#34 /var/sites/e/exceltraining.london/public_html/flarum2/index.php(22): Flarum\Http\Server->listen()
#35 {main}  
[2020-01-06 16:38:51] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:40:48] production.ERROR: Exception: Connecting failed in /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flagrow/bazaar/src/Api/Controllers/ConnectController.php:35
Stack trace:
#0 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): Extiverse\Bazaar\Api\Controllers\ConnectController->handle(Object(Zend\Diactoros\ServerRequest))
#1 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(65): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}(Object(Zend\Diactoros\ServerRequest), Array)
#2 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\DispatchRoute->process(Object(Zend\Diactoros\ServerRequest), Object(Closure))
#3 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#4 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\SetLocale->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#5 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(23): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#6 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\CheckCsrfToken->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#7 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#8 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\AuthenticateWithHeader->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#9 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#10 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\AuthenticateWithSession->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#11 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(51): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#12 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\RememberFromCookie->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#13 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#14 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\StartSession->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#15 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#16 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Api\Middleware\FakeHttpMethods->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#17 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#18 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\ParseJsonBody->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#19 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#20 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Flarum\Http\Middleware\HandleErrors->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#21 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(83): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#22 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/middlewares/request-handler/src/RequestHandler.php(84): Zend\Stratigility\MiddlewarePipe->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#23 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\RequestHandler->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#24 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#25 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\BasePathRouter->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#26 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Middleware/OriginalMessages.php(41): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#27 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Zend\Stratigility\Middleware\OriginalMessages->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#28 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/middlewares/base-path/src/BasePath.php(53): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#29 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/Next.php(60): Middlewares\BasePath->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\Next))
#30 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(83): Zend\Stratigility\Next->handle(Object(Zend\Diactoros\ServerRequest))
#31 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(72): Zend\Stratigility\MiddlewarePipe->process(Object(Zend\Diactoros\ServerRequest), Object(Zend\Stratigility\EmptyPipelineHandler))
#32 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/zendframework/zend-httphandlerrunner/src/RequestHandlerRunner.php(95): Zend\Stratigility\MiddlewarePipe->handle(Object(Zend\Diactoros\ServerRequest))
#33 /var/sites/e/exceltraining.london/public_html/flarum2/vendor/flarum/core/src/Http/Server.php(44): Zend\HttpHandlerRunner\RequestHandlerRunner->run()
#34 /var/sites/e/exceltraining.london/public_html/flarum2/index.php(22): Flarum\Http\Server->listen()
#35 {main}  
[2020-01-06 16:46:05] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:46:17] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:50:59] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 16:56:41] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 17:00:15] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 17:05:08] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  
[2020-01-06 17:09:26] production.ALERT: Failed Bazaar call to flagrow.io: Forbidden  

</details>

**Comment by luceos** [comment]
Can you give me an idea where your site is installed, does it perhaps have outgoing connections disabled?

**Comment by darossi81** [comment]
It's on shared hosting with tsohost (similar to bluehost etc).

**Comment by darossi81** [comment]
I just increased my PHP memory limit and it seems to be working!

**Comment by luceos** [comment]
That is so .. odd; why would the request to flagrow.io return a Forbidden when there's not enough memory.

Can you clarify why you decided to increase the memory limit @darossi81 ?

**Comment by darossi81** [comment]
I spoke too soon.... I briefly saw the list of extensions in Bazaar but when I refreshed the page they are not showing again....

**Comment by darossi81** [comment]
> That is so .. odd; why would the request to flagrow.io return a Forbidden when there's not enough memory.
> 
> Can you clarify why you decided to increase the memory limit @darossi81 ?

There was a red icon at the top of the page stating that my PHP was only allowing 128MB so I increased it to 1GB.  That red icon isn't showing any more and the list of extensions briefly appeared but now seems to have gone again (although the red warning icon is no longer present).

**Comment by darossi81** [comment]
![bazaar](https://user-images.githubusercontent.com/48297724/71885953-44778c80-3133-11ea-934f-d3ea7a03944b.PNG)

As per screengrab, they are appearing again now (I logged out and back in)

**Comment by darossi81** [comment]
It seems to be a little unstable - if I try and search for an extension in Bazaar, the screen goes blank and then I have to disable Bazaar, log out, log back in and enable it again

**Comment by darossi81** [comment]
![installing from bazaar](https://user-images.githubusercontent.com/48297724/71886636-776e5000-3134-11ea-93d3-eaeec721d2ad.PNG)

Here's what happened when I tried to install one.

**Comment by luceos** [comment]
Somehow your hosting plan is restricted, that's my assumption. Bazaar tries to resolve issues with shared hosting plans, but in the background still relies on composer. Your best bet would be to install and manage Flarum locally and then upload everything to your hosting plan.

I'm aware about the issues around Bazaar/Flagrow.io and have plans to resolve them with the successor extiverse.

**Comment by darossi81** [comment]
Thanks for the assistance.  My site isn't live or anything, I'm just exploring the different options. Flarum looks great by the way and is the best I've looked at so far :)
