### ISSUE TITLE
InvalidArgumentException. Cannot identify 268435456.

### ISSUE THREAD

**Issue by CyberVits** [extiverse/bazaar#144]
Problem with Bazaar. Installation was successful. But after activating this extension, an error appears: "An error occurred while trying to load this page." How can i fix this?
![scr12](https://user-images.githubusercontent.com/33093217/80896649-40cacf80-8cf9-11ea-95fa-68fbd938758b.png)

**Comment by luceos** [comment]
Your server has a very odd memory limit set. Bazaar needs an update to support that. But bazaar will most likely be removed soon anyway as an extension pending a successor from extiverse. Sorry.

**Comment by CyberVits** [comment]
> extiverse

Ok, thank you.

**Comment by CyberVits** [comment]
> Your server has a very odd memory limit set. Bazaar needs an update to support that. But bazaar will most likely be removed soon anyway as an extension pending a successor from extiverse. Sorry.

Ok, thank you.
